### ISSUE TITLE
Creation of Labels

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#105]
Creating many labels on Github is quite painful and a project may need many labels: version labels, assignees labels etc. Let's make comdor create the labels specified in ``.comdor.yml``.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#107](https://github.com/amihaiemil/comdor/issues/107) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil the only puzzle [#107](https://github.com/amihaiemil/comdor/issues/107) is solved here.
