### ISSUE TITLE
JsonMention.java:40-41: Implement method scripts(), which...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/comdor#12]
The puzzle `9-a14ec7c0` (from #9) in [`src/main/java/co/comdor/github/JsonMention.java`](https://github.com/amihaiemil/comdor/blob/master/src/main/java/co/comdor/github/JsonMention.java) (lines 40-41) has to be resolved: "Implement method scripts(), which extracts the code to run from the comment, and write some unit tests for it."

The puzzle was created by Mihai Andronache on 28-Oct-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
@comdor hello there

**Comment by amihaiemil** [comment]
@comdor hello there

**Comment by comdor** [comment]
@amihaiemil Hi there! I'm only version `0.0.1`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@comdor how are you?

**Comment by comdor** [comment]
@amihaiemil Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by amihaiemil** [comment]
@comdor hello

**Comment by comdor** [comment]
amihaiemil Hi there! I'm only version `0.0.2`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@comdor run

**Comment by comdor** [comment]
@amihaiemil I received your command, but I am only version `0.0.2`, I cannot run it yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@comdor run ``cloc .``

**Comment by comdor** [comment]
@amihaiemil Only commanders or architects can give such a command! More details [here](http://www.comdor.co/config.html).

**Comment by charlesmike** [comment]
@comdor run something

**Comment by comdor** [comment]
@charlesmike Thank you for the command!

@amihaiemil Please approve this.

**Comment by charlesmike** [comment]
> @charlesmike Thank you for the command!

@amihaiemil Please approve this.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by comdor** [comment]
@charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by charlesmike** [comment]
> @charlesmike Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

@comdor sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.

**Comment by amihaiemil** [comment]
@comdor hello

**Comment by comdor** [comment]
@amihaiemil Hi there! I'm only version `0.0.2`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.
