### ISSUE TITLE
QA Task With Wrong Initial Assignee

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#123]
A QA Task with a wrong assignee (doesn't have this role).

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. Unfortunately, @amihaiemil is not a contributor with the required role (DEV), that's why I unassigned them. 

I will assign a contributor to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
