### ISSUE TITLE
Implement hello

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#3]
Let's enable it to respond to hello commands.
We should follow charlesmike's architecture, based on Steps: https://github.com/opencharles/charles-rest/blob/master/architecture.md

**Comment by amihaiemil** [comment]
@comdor hi

**Comment by comdor** [comment]
@amihaiemil Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by amihaiemil** [comment]
@comdor hello, how are you?

**Comment by comdor** [comment]
@amihaiemil Hi there! I'm only version `0.0.1`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.
