### ISSUE TITLE
Tag Github users

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#44]
Currently, the github users (command's author, or architects) are not tagged with ``@``, in the comments. There should be interface

**Comment by amihaiemil** [comment]
@comdor hello

**Comment by comdor** [comment]
@amihaiemil Hi there! I'm only version `0.0.2`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@comdor run ``cloc .``

**Comment by comdor** [comment]
@amihaiemil Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.
