### ISSUE TITLE
It doesn't understand "run"

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#47]
By now, it should understand the "run" command. FInd and fix the issue. See [here](https://github.com/amihaiemil/comdor/issues/44#issuecomment-343286845)

**Comment by amihaiemil** [comment]
@comdor run this pls

**Comment by comdor** [comment]
@amihaiemil Sorry, I do not understand what you mean. Check the [documentation](http://comdor.co/doc.html) for more details.

**Comment by amihaiemil** [comment]
@comdor run ``cloc .`` pls

**Comment by comdor** [comment]
@amihaiemil For this command there has to be at least one architect defined,whom I should ask for approval! More details [here]().

**Comment by amihaiemil** [comment]
@comdor run cloc . pls

**Comment by comdor** [comment]
@amihaiemil I received your command, but I am only version `0.0.2`, I cannot run it yet.Follow me and [my website](http://comdor.co) for updates on the next version.
