### ISSUE TITLE
Cleanup useless dependencies

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#52]
Some dependencies are included in the deployable, yet are also provided by the JavaEE runtime (e.g. jcabi-github brings in ``org.glassfish:javax.json``)

**Comment by amihaiemil** [comment]
@comdor run ``cloc .``

**Comment by comdor** [comment]
@amihaiemil I received your command, but I am only version `0.0.2`, I cannot run it yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@comdor hello

**Comment by comdor** [comment]
@amihaiemil Hi there! I'm only version `0.0.2`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@comdor run ``cloc .``

**Comment by comdor** [comment]
@amihaiemil I received your command, but I am only version `0.0.2`, I cannot run it yet. Follow me and [my website](http://comdor.co) for updates on the next version.
