### ISSUE TITLE
Use docker-java-api

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/comdor#99]
We should use [docker-java-api](https://www.github.com/amihaiemil/docker-java-api) now that we have the very first version released.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#103](https://github.com/amihaiemil/comdor/issues/103) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil the only puzzle [#103](https://github.com/amihaiemil/comdor/issues/103) is solved here.
